# Generated by Django 2.2.5 on 2020-04-29 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('video', models.FileField(null=True, upload_to='media/pitcher_app/videos/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(default='active', max_length=15)),
            ],
        ),
    ]
